In [1]:
import numpy as np
import pandas as pd

In [2]:
data_set = pd.read_csv('breast-cancer-wisconsin.csv',na_values=['?'])

In [3]:
data_set.head()

ID  clumb_thickness  cell_size  cell_shape  marg_adhesion   
0  1000025                5          1           1              1  \
1  1002945                5          4           4              5   
2  1015425                3          1           1              1   
3  1016277                6          8           8              1   
4  1017023                4          1           1              3   

   Epethilial_cell_size  bare_nuclie  chromatin  norm_nucliolie  mitoses   
0                     2          1.0          3               1        1  \
1                     7         10.0          3               2        1   
2                     2          2.0          3               1        1   
3                     3          4.0          3               7        1   
4                     2          1.0          3               1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

class

2---benign
4---malignant


# DATA CLEANING

row deletion 
column deletion


In [4]:
# we will search and delete the rows whose class is classified other than 2 or 4


# there is data cleaning needed to this data set

# idhe maam

# there is ? in a column so set this value as a null

#data_set = data_set.replace({'?':np.nan})

In [5]:
data_set.isnull().sum()

ID                       0
clumb_thickness          0
cell_size                0
cell_shape               0
marg_adhesion            0
Epethilial_cell_size     0
bare_nuclie             16
chromatin                0
norm_nucliolie           0
mitoses                  0
class                    0
dtype: int64

In [6]:
# count the number of rows with NaN values in column 'B'
num_rows_with_nan = data_set['bare_nuclie'].isnull().sum()
num_rows_with_nan

16

In [7]:
#there are 16 rows with a null value in bare_nuclie column
# ill replace null value with the mean value of that column

mean_val = data_set['bare_nuclie'].mean()
mean_val

3.5446559297218156

In [8]:
data_set["bare_nuclie"] = data_set.bare_nuclie.fillna(int(mean_val))

In [10]:
data_set.isnull().sum()

ID                      0
clumb_thickness         0
cell_size               0
cell_shape              0
marg_adhesion           0
Epethilial_cell_size    0
bare_nuclie             0
chromatin               0
norm_nucliolie          0
mitoses                 0
class                   0
dtype: int64

In [11]:
# split the data into features and target

features = data_set.iloc[:,:-1].values
target = data_set.iloc[:,-1:].values


In [12]:
features


array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 3.000000e+00,
        2.000000e+00, 1.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 8.000000e+00,
        1.000000e+01, 2.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        6.000000e+00, 1.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        4.000000e+00, 1.000000e+00]])

In [13]:
target

array([[2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [2],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [2],
       [4],
       [2],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    

Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

In [16]:
print(len(x_train),len(y_train))

489 489


In [17]:
print(len(x_test),len(y_test))

210 210


In [18]:
x_train

array([[8.593500e+05, 8.000000e+00, 1.000000e+01, ..., 7.000000e+00,
        3.000000e+00, 8.000000e+00],
       [1.315807e+06, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        1.000000e+01, 1.000000e+01],
       [5.614770e+05, 1.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       ...,
       [3.908400e+05, 8.000000e+00, 4.000000e+00, ..., 3.000000e+00,
        9.000000e+00, 2.000000e+00],
       [1.294562e+06, 1.000000e+01, 8.000000e+00, ..., 5.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.167471e+06, 4.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00]])

Data preprocessing


In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
# Perform feature scaling and normalization
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [21]:
X_train

array([[-0.31022316,  1.23203096,  2.25737003, ...,  1.3873881 ,
         0.0493974 ,  3.93974808],
       [ 0.3304376 ,  0.16698121,  2.25737003, ...,  2.57692542,
         2.36566183,  5.16333449],
       [-0.72830316, -1.25308511, -0.71708671, ..., -0.19866165,
        -0.61239244, -0.34280437],
       ...,
       [-0.96780093,  1.23203096,  0.27439887, ..., -0.19866165,
         2.03476692,  0.26898883],
       [ 0.30061915,  1.94206413,  1.59637965, ...,  0.59436323,
        -0.61239244, -0.34280437],
       [ 0.12224043, -0.18803537, -0.71708671, ..., -0.19866165,
        -0.61239244, -0.34280437]])

In [22]:
X_test

array([[ 0.15903031, -1.25308511, -0.71708671, ..., -0.99168653,
        -0.61239244, -0.34280437],
       [ 0.1930931 , -0.18803537, -0.71708671, ..., -0.59517409,
        -0.61239244, -0.34280437],
       [ 0.13447378, -0.54305195, -0.71708671, ..., -0.19866165,
        -0.61239244, -0.34280437],
       ...,
       [ 0.35607206, -0.18803537, -0.71708671, ..., -0.59517409,
        -0.61239244, -0.34280437],
       [ 0.17087909, -0.18803537, -0.71708671, ..., -0.19866165,
        -0.61239244, -0.34280437],
       [-0.05236555, -0.54305195, -0.71708671, ..., -0.59517409,
        -0.61239244, -0.34280437]])

# selecting the best hyperparameter using randomizzed search

In [23]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from scipy.stats import randint as sp_randint

In [24]:
rf_classifier = RandomForestClassifier()

In [25]:
# Define the hyperparameter grid
param_dist = {'n_estimators': sp_randint(10, 100),
              'max_depth': sp_randint(1, 50),
              'max_features': ['sqrt', 'log2', 6],
              'min_samples_split': sp_randint(2, 20),
              'min_samples_leaf': sp_randint(1, 10),
              'criterion': ['gini', 'entropy']}

# Perform a randomized search with 5-fold cross-validation
random_search = RandomizedSearchCV(rf_classifier, param_distributions=param_dist,
                                   n_iter=100, cv=5, random_state=42, n_jobs=-1)

In [26]:
y_train=y_train.reshape(-1)

In [27]:
# Fit the randomized search object to the data
random_search.fit(X_train, y_train)

# Print the best hyperparameters and the corresponding accuracy
print('Best hyperparameters:', random_search.best_params_)
print('Best accuracy:', random_search.best_score_)

Best hyperparameters: {'criterion': 'gini', 'max_depth': 21, 'max_features': 'sqrt', 'min_samples_leaf': 7, 'min_samples_split': 17, 'n_estimators': 66}
Best accuracy: 0.9692825583841784


use the above generated hyperparameter for training 

In [28]:
# Train the random forest model
rf_classifier = RandomForestClassifier(n_estimators=98, max_depth=49, max_features='log2',criterion='gini',min_samples_leaf=4,min_samples_split=17)
rf_classifier.fit(X_train, y_train)


RandomForestClassifier(max_depth=49, max_features='log2', min_samples_leaf=4,
                       min_samples_split=17, n_estimators=98)

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [31]:
# Evaluate the model
y_pred = rf_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
#precision = precision_score(y_test, y_pred, pos_label=[2,4])
#recall = recall_score(y_test, y_pred)
accuracy

0.9761904761904762